### ISSUE TITLE
Courses Section

### ISSUE THREAD

**Issue by kj3moraes** [xtellurian/QuantumResources#5]
A suggested improvement would be a courses section. This would help for new / intermediate learners. There are several free courses / lecture series online such as : 

- [Quantum Country](https://quantum.country/)  
- John Preskill's [Course Notes from Caltech CS 219](http://theory.caltech.edu/~preskill/ph219/index.html#lecture) 
- [Qiskit Textbook](https://qiskit.org/textbook/ch-states/introduction.html)

**Comment by xtellurian** [comment]
Sounds good. I'm happy to accept a PR with that included.

**Comment by kj3moraes** [comment]
Done

**Comment by xtellurian** [comment]
#6

**Comment by xtellurian** [comment]
Thanks for your contribution 😀
